[phases.setup]
nixPkgs = ["sqlite"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python src/langchain_web_app.py"
